/* Every palette is fully iconned, or none of them ship (ticket 50).

   The mark's files are generated - `npm run render:mark` - and generated by
   hand rather than in CI, because rasterising needs a Chromium and the
   output is tracked. That trade only works if forgetting the run fails
   somewhere loud, which is this file. A ninth palette added to palettes.css
   and merged without a run would otherwise reach a person's phone as a
   launcher icon resource that does not resolve, and reach a tab as a
   favicon href pointing at nothing - and a broken favicon href fails
   silently, leaving whatever icon the tab already had.

   Greps by design (ticket 08): what is asserted is that a file exists and
   that a manifest names a component, which is data, with nothing to run.
   Whether the drawing inside is right is mark.test.ts's question. */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = new URL('../', import.meta.url);
const read = (path: string) => readFileSync(new URL(path, root), 'utf8');
const exists = (path: string) => existsSync(fileURLToPath(new URL(path, root)));

/** The eight flags, off the stylesheet that owns them - the same read
    render-mark.mjs and documentChrome do, so this cannot be testing a
    different set from the one that ships. */
const palettes = [...read('src/lib/theme/palettes.css').matchAll(/\[data-palette="([a-z]+)"\]\s*\{\s*--motif-stripes:/g)]
  .map((match) => match[1]);

const manifest = read('android/app/src/main/AndroidManifest.xml');

/** LauncherDefault is the default palette's alias, so trans has no alias of
    its own: an install that never changes its flag never flips one. */
const DEFAULT_PALETTE = 'trans';
const capitalised = (flag: string) => flag[0].toUpperCase() + flag.slice(1);

describe('the mark is generated for every palette the app ships', () => {
  it('finds all 8 palettes - the parser has drifted otherwise', () => {
    expect(palettes).toHaveLength(8);
    expect(palettes).toContain(DEFAULT_PALETTE);
  });

  it('has a tab icon on disk for each one', () => {
    for (const flag of palettes) expect(exists(`static/favicon-${flag}.svg`), flag).toBe(true);
  });

  it('has an Android adaptive icon and its foreground on disk for each one', () => {
    for (const flag of palettes) {
      expect(exists(`android/app/src/main/res/drawable/ic_launcher_${flag}_foreground.xml`), flag).toBe(true);
      const icon =
        flag === DEFAULT_PALETTE
          ? 'ic_launcher'
          : `ic_launcher_${flag}`;
      expect(exists(`android/app/src/main/res/mipmap-anydpi-v26/${icon}.xml`), flag).toBe(true);
      expect(read(`android/app/src/main/res/mipmap-anydpi-v26/${icon}.xml`), flag)
        .toContain(`@drawable/ic_launcher_${flag}_foreground`);
    }
  });

  it('has a launcher activity-alias naming that icon for each one', () => {
    for (const flag of palettes) {
      if (flag === DEFAULT_PALETTE) continue;
      expect(manifest, flag).toContain(`android:name=".disguise.Launcher${capitalised(flag)}"`);
      expect(manifest, flag).toContain(`android:icon="@mipmap/ic_launcher_${flag}"`);
    }
  });

  it('starts with exactly one alias enabled, and it is the default one', () => {
    /* What a fresh install shows before any preference has ever synced. Two
       enabled aliases would put the app in the launcher twice; none would
       leave it with no way in at all. DisguiseAliasTest proves the same
       invariant on a device across every flip; this proves the state the
       device test starts from. */
    const aliases = [...manifest.matchAll(/<activity-alias[\s\S]*?<\/activity-alias>/g)].map((m) => m[0]);
    expect(aliases).toHaveLength(palettes.length + 1);
    const enabled = aliases.filter((alias) => /android:enabled="true"/.test(alias));
    expect(enabled).toHaveLength(1);
    expect(enabled[0]).toContain('.disguise.LauncherDefault');
  });

  it('keeps the review set out of static/, where everything ships', () => {
    /* brand/mark/ is 26 SVGs and 74 raster files. Everything under static/
       goes into the web build and into the APK's assets, so the review set
       living there would be two megabytes on every install. */
    expect(exists('brand/mark/README.md')).toBe(true);
    expect(exists('static/brand')).toBe(false);
  });
});
