/* The first frame, as CSS (phase 14 pre-release ticket 13).

   Until the app's JavaScript has run nothing on screen carries a colour: the
   token layer is imported by the app, so the document is white for as long as
   the scripts take to arrive, 3.4 to 3.7 s on a slow phone. app.html now
   ships a ground and the mark as markup and CSS of its own, so the browser
   paints them as soon as the document is parsed, and the app fades them out
   once boot has answered (lib/splash.ts does that).

   The colours cannot be imported: they have to be in the document itself.
   They are generated from palettes.css instead of copied by hand, between the
   two markers in src/app.html, by `npm run render:splash`, and
   tests/splash.test.ts fails when the block no longer says what this file
   would write. Dropping a palette or retuning a ground therefore cannot
   leave the first frame wearing last release's colours.

   What is drawn is the mark's own corner sun (mark.ts owns the rule and the
   numbers): one ring per stripe of the flag, a black seam on the outer side
   of each, centred on the tile's top right corner, in a white tile with a
   black edge. As CSS gradients rather than the SVG, because the document is
   the critical path and sixteen inline SVGs would be most of it. The seam
   and the radii are mark.ts's constants and ringRadii, so the two drawings
   share their numbers, and the review page for this ticket lays the two over
   each other.

   The mark does not move, here or on the way out: it only fades, with the
   ground, the way the logo is never animated (ticket 38). */

import { MARK_R, MARK_SEAM } from '../components/mark.ts';
import { ringRadii } from '../motion/flagSun.ts';

export const SPLASH_BEGIN = '/* splash:begin (generated by scripts/render-splash.mjs, do not edit) */';
export const SPLASH_END = '/* splash:end */';

/** What the first frame needs to know about one flag. */
export interface SplashPalette {
  name: string;
  stripes: string[];
  light: string;
  dark: string;
}

/** Every palette, read out of palettes.css: its stripes and the ground
    (`--bg`) it gives each theme. */
export function readSplashPalettes(css: string): SplashPalette[] {
  const stripes = new Map<string, string[]>();
  for (const m of css.matchAll(/\[data-palette="([a-z]+)"\]\s*\{\s*--motif-stripes:\s*([^;]+);/g)) {
    stripes.set(m[1], m[2].split(',').map((s) => s.trim()));
  }
  const ground = (name: string, theme: 'light' | 'dark') => {
    const m = css.match(
      new RegExp(`\\[data-palette="${name}"\\]\\[data-theme="${theme}"\\]\\s*\\{[^}]*?--bg:\\s*(#[0-9A-Fa-f]{6})`)
    );
    if (!m) throw new Error(`palettes.css gives ${name} no --bg in ${theme}`);
    return m[1].toUpperCase();
  };
  return [...stripes].map(([name, list]) => ({ name, stripes: list, light: ground(name, 'light'), dark: ground(name, 'dark') }));
}

const num = (value: number) => String(+value.toFixed(2));

/** The sun's colour stops. From the corner outwards, the innermost ring's
    colour up to its outer seam, then black for the seam, then the next ring.
    Every stop is a percentage of the 100 unit tile, which is the gradient's
    radius, so it holds at any `--s`. Only the stops are the palette's: the
    gradient around them is written once in app.html, where `--s` exists to
    be read (a custom property holding `var(--s)` is resolved on the element
    that declares it, which is <html>, and finds nothing). */
export function sunStops(stripes: string[]): string {
  const radii = ringRadii(stripes.length, MARK_R);
  const stops: string[] = [];
  for (let i = stripes.length - 1; i >= 0; i--) {
    const inner = i === stripes.length - 1 ? 0 : radii[i + 1];
    stops.push(`${stripes[i]} ${num(inner)}% ${num(radii[i] - MARK_SEAM)}%`, `#000 ${num(radii[i] - MARK_SEAM)}% ${num(radii[i])}%`);
  }
  return stops.join(',');
}

/** The block between the markers, markers included. */
export function splashBlock(palettes: SplashPalette[]): string {
  const rules = palettes.flatMap((p) => [
    `[data-palette=${p.name}]{--splash-rings:${sunStops(p.stripes)}}`,
    `[data-palette=${p.name}][data-theme=light]{--splash-ground:${p.light}}`,
    `[data-palette=${p.name}][data-theme=dark]{--splash-ground:${p.dark}}`
  ]);
  return [SPLASH_BEGIN, ...rules, SPLASH_END].join('\n');
}

/** The build's module hints, made inert: `rel="modulepreload"` becomes
    `rel="x-modulepreload"`, which the browser ignores, and the pre-paint
    script in app.html gives it back after the first frame has painted.

    Why: the document names 98 modules and six stylesheets, and the browser
    fetches all of them at once over one connection, sharing it out evenly.
    The stylesheets are what a first paint waits for (the largest is 125 KB),
    and they were arriving at 2.5 s because they queued with the modules,
    which nothing waits for yet. Measured on the 4x CPU, 1.6 Mbps, 150 ms
    profile over HTTP/2: first paint 2.4 s with the hints live, 0.7 s with
    them held until after DOMContentLoaded, and the app's own first screen
    no later (3.6 s against 3.4 to 3.9 s) - the same bytes cross the same
    pipe, only in a better order. */
export function holdModulePreloads(html: string): string {
  return html.replaceAll('rel="modulepreload"', 'rel="x-modulepreload"');
}
