/* The first frame, as CSS (phase 14 pre-release ticket 13).

   Until the app's JavaScript has run nothing on screen carries a colour: the
   token layer is imported by the app, so the document is white for as long as
   the scripts take to arrive, 3.4 to 3.7 s on a slow phone. app.html now
   ships a ground and the mark as markup and CSS of its own, so the browser
   paints them as soon as the document is parsed, and the app fades them out
   once boot has answered (lib/splash.ts does that).

   The colours cannot be imported: they have to be in the document itself.
   They are generated from palettes.css instead of copied by hand, between the
   two markers in src/app.html, by `npm run render:splash`, and
   tests/splash.test.ts fails when the block no longer says what this file
   would write. Dropping a palette or retuning a ground therefore cannot
   leave the first frame wearing last release's colours.

   What is drawn is the mark's own corner sun (mark.ts owns the rule and the
   numbers): one ring per stripe of the flag, a black seam on the outer side
   of each, centred on the tile's top right corner, in a white tile with a
   black edge. As CSS gradients rather than the SVG, because the document is
   the critical path and sixteen inline SVGs would be most of it. The seam
   and the radii are mark.ts's constants and ringRadii, so the two drawings
   share their numbers, and the review page for this ticket lays the two over
   each other.

   The mark does not move, here or on the way out: it only fades, with the
   ground, the way the logo is never animated (ticket 38). */

import { MARK_R, MARK_SEAM, MARK_TILE, MARK_TILE_RADIUS } from '../components/mark.ts';
import { ringRadii } from '../motion/flagSun.ts';

export const SPLASH_BEGIN = '/* splash:begin (generated by scripts/render-splash.mjs, do not edit) */';
export const SPLASH_END = '/* splash:end */';

/** What the first frame needs to know about one flag. */
export interface SplashPalette {
  name: string;
  stripes: string[];
  light: string;
  dark: string;
}

/** Every palette, read out of palettes.css: its stripes and the ground
    (`--bg`) it gives each theme. */
export function readSplashPalettes(css: string): SplashPalette[] {
  const stripes = new Map<string, string[]>();
  for (const m of css.matchAll(/\[data-palette="([a-z]+)"\]\s*\{\s*--motif-stripes:\s*([^;]+);/g)) {
    stripes.set(m[1], m[2].split(',').map((s) => s.trim()));
  }
  const ground = (name: string, theme: 'light' | 'dark') => {
    const m = css.match(
      new RegExp(`\\[data-palette="${name}"\\]\\[data-theme="${theme}"\\]\\s*\\{[^}]*?--bg:\\s*(#[0-9A-Fa-f]{6})`)
    );
    if (!m) throw new Error(`palettes.css gives ${name} no --bg in ${theme}`);
    return m[1].toUpperCase();
  };
  return [...stripes].map(([name, list]) => ({ name, stripes: list, light: ground(name, 'light'), dark: ground(name, 'dark') }));
}

/** The seam and the tile's edge. mark.ts writes it as a literal `#000` in
    markSvg and cropMarkup, with no constant to import, so it is stated once
    here and tests/splash.test.ts reads mark.ts to hold the two together. */
export const SPLASH_INK = '#000';

const num = (value: number) => String(+value.toFixed(2));

/** The sun's colour stops. From the corner outwards, the innermost ring's
    colour up to its outer seam, then black for the seam, then the next ring.
    Every stop is a percentage of the 100 unit tile, which is the gradient's
    radius, so it holds at any `--s`. Only the stops are the palette's: the
    gradient around them is written once in app.html, where `--s` exists to
    be read (a custom property holding `var(--s)` is resolved on the element
    that declares it, which is <html>, and finds nothing). */
export function sunStops(stripes: string[]): string {
  const radii = ringRadii(stripes.length, MARK_R);
  const stops: string[] = [];
  for (let i = stripes.length - 1; i >= 0; i--) {
    const inner = i === stripes.length - 1 ? 0 : radii[i + 1];
    stops.push(`${stripes[i]} ${num(inner)}% ${num(radii[i] - MARK_SEAM)}%`, `${SPLASH_INK} ${num(radii[i] - MARK_SEAM)}% ${num(radii[i])}%`);
  }
  /* Past the outermost seam is the tile, which is white (MARK_TILE): a
     gradient holds its last colour, so it has to be said. */
  stops.push(`${MARK_TILE} 100%`);
  return stops.join(',');
}

/** The block between the markers, markers included. */
export function splashBlock(palettes: SplashPalette[]): string {
  const rules = palettes.flatMap((p) => [
    `[data-palette=${p.name}]{--splash-rings:${sunStops(p.stripes)}}`,
    `[data-palette=${p.name}][data-theme=light]{--splash-ground:${p.light}}`,
    `[data-palette=${p.name}][data-theme=dark]{--splash-ground:${p.dark}}`
  ]);
  /* The tile and the edge, from mark.ts, for the static CSS around this block
     to read: not a second copy of a colour or a radius to keep in step. */
  const tile = `#splash{--splash-tile:${MARK_TILE};--splash-ink:${SPLASH_INK};--splash-radius:${MARK_TILE_RADIUS}%}`;
  return [SPLASH_BEGIN, tile, ...rules, SPLASH_END].join('\n');
}
