<script lang="ts">
  /* The licence notices (phase 15 release-blockers ticket 10), reached from
     About. Everything the build bundled, the Android libraries around the
     WebView and the fonts, each with the licence and notice text its terms
     ask to travel with it. The list is generated by the build itself
     (vite.config.ts, scripts/licence-notices.mjs) and arrives in this
     screen's own chunk, so there is no read to wait on and nothing to
     reserve space for.

     A row opens its texts in a sheet rather than unfolding in place: a
     licence runs to a few hundred lines, and an Apache text opening inside
     a list of a hundred names would push every row under it off the
     screen. The chosen entry stays set while the sheet leaves, so its text
     goes down with it instead of blanking first. */
  import notices from 'virtual:licence-notices';
  import type { NoticeEntry, NoticeSection } from '$lib/licences/notices';
  import { m } from '$lib/paraglide/messages';
  import { isAndroid } from '$lib/platform';
  import ScreenHeader from '$lib/components/ScreenHeader.svelte';
  import Sheet from '$lib/components/Sheet.svelte';
  import ListCard from '$lib/components/kit/ListCard.svelte';
  import ListRow from '$lib/components/kit/ListRow.svelte';
  import SectionHeading from '$lib/components/kit/SectionHeading.svelte';

  const heading: Record<NoticeSection['id'], () => string> = {
    app: () => m.licences_section_app(),
    android: () => m.licences_section_android(),
    fonts: () => m.licences_section_fonts()
  };

  /* The Android libraries only ship inside the APK, so a browser shows the
     two sections it actually received. */
  let sections = $derived(
    notices.sections.filter((section) => section.entries.length && (section.id !== 'android' || isAndroid()))
  );

  let open = $state(false);
  let chosen = $state<NoticeEntry | null>(null);

  const facts = (entry: NoticeEntry) => (entry.version ? `${entry.version} · ${entry.licence}` : entry.licence);

  function show(entry: NoticeEntry) {
    chosen = entry;
    open = true;
  }
</script>

<div class="screen">
  <ScreenHeader title={m.licences_title()} back="/settings" />

  <p class="licences-intro muted small">{m.licences_intro()}</p>

  {#each sections as section (section.id)}
    <SectionHeading text={heading[section.id]()} />
    <ListCard>
      {#each section.entries as entry (entry.name + entry.version)}
        <ListRow
          key="licence"
          title={entry.name}
          subtitle={facts(entry)}
          data-licence={entry.name}
          onclick={() => show(entry)}
        />
      {/each}
    </ListCard>
  {/each}

  <Sheet bind:open title={chosen?.name ?? ''}>
    {#if chosen}
      <h3 class="licence-name" translate="no">{chosen.name}</h3>
      <p class="muted small licence-facts" translate="no">{facts(chosen)}</p>
      {#each chosen.texts as index (index)}
        <pre class="licence-text" translate="no" data-licence-text>{notices.texts[index]}</pre>
      {/each}
    {/if}
  </Sheet>
</div>

<style>
  .licences-intro {
    margin: 0 0 var(--space-4);
    line-height: 1.55;
  }

  .licence-name {
    margin: 0;
    overflow-wrap: anywhere;
  }

  .licence-facts {
    margin: var(--space-1) 0 var(--space-4);
  }

  /* A licence keeps its own line breaks: lists, numbered sections and the
     all-caps warranty paragraph read as written. Wrapped rather than
     scrolled sideways, so nothing is ever off the edge of a phone. In the
     body face at the reading size rather than a 12px monospace: these are
     read, not compared column by column, and a narrow monospace column at
     390px set the MIT text in 38-character lines. */
  .licence-text {
    margin: 0 0 var(--space-4);
    padding: var(--space-4);
    border-radius: var(--r-block);
    background: var(--surface-2);
    color: var(--text);
    font-family: var(--font-body);
    font-size: var(--text-sm);
    line-height: 1.55;
    white-space: pre-wrap;
    overflow-wrap: anywhere;
  }
</style>
